language: python
cache: pip
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
stages:
  - name: test
  - name: deploy to pypi
    if: type = push AND tag =~ ^\d+\.\d+\.\d+
jobs:
  include:
    - stage: deploy to PyPI
      install: sudo apt-get install ffmpeg
      script: skip

      deploy:
        provider: pypi
        username: __token__
        password: pypi-AgEIcHlwaS5vcmcCJGZmZjI0ZjJjLTE4OGEtNDRlYS05NWI0LTRiMmYxOGRmZmQ2NgACQnsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJhcmRpY3NydGNvbGxlY3RvciJdfSwgInZlcnNpb24iOiAxfQAABiDdBJJ1ApODRyaus_M70ZoY2nWYqiWcXpHnvzV27nonzg
        distributions: sdist bdist_wheel # Your distributions here
        twine_check: true
        on:
          tags: true
          repo: IoT-Ignite/ArdicSrtCollector
before_install:
  - sudo apt-get install ffmpeg
install:
  - pip3 install -e .
script: python3 test/test_package.py
notifications:
  email:
    on_success: never
    on_failure: change